export const SmeList = [
  {
    category: "Furniture",
    name: "iDEA",
    color: "yellow",
    link: "http://www.google.com",
    description: "Best Furniture Company",
  },
  {
    category: "Furniture",
    name: "WeWood",
    color: "yellow",
    link: "http://www.google.com",
    description: "Best Furniture Company",
  },
  {
    category: "Health",
    name: "Helth",
    color: "green",
    link: "http://www.google.com",
    description: "Health Guru",
  },
  {
    category: "Health",
    name: "Super Supplements",
    color: "green",
    link: "http://www.google.com",
    description: "Health Guru",
  },
  {
    category: "Food",
    name: "Shake Shag",
    color: "blue",
    link: "http://www.google.com",
    description: "Hamburger Chain",
  },
  {
    category: "Beverages",
    name: "Miss Kokonut",
    color: "blue",
    link: "http://www.google.com",
    description: "Handmade Coconut Shake",
  },
  {
    category: "Food",
    name: "Seafood Market",
    color: "blue",
    link: "http://www.google.com",
    description: "Seafood",
  },
];
